### ISSUE TITLE
License violation - this codebase is stolen

### ISSUE THREAD

**Issue by Rainson12** [Sethuramalingam-art/Banking-FinanceManagement#1]
This codebase is stolen from @adrianhajdin the original repo is located here: https://github.com/adrianhajdin/banking
License reminder:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by Sethuramalingam-art** [comment]
> This codebase is stolen from @adrianhajdin the original repo is located here: https://github.com/adrianhajdin/banking
> 
> License reminder:
> 
> ```
> 
> The above copyright notice and this permission notice shall be included in all
> 
> copies or substantial portions of the Software.
> 
> ```

Yes I followed/ learned the tutorial and implemented the same for 2-3 months. And @Rainson12 it is not stolen I have learnt step by step and coded by watching his tutorial. And source of project code not copied, I spent time to code. Please remove this comment. You can see my commits how many commits I did.
